package service

// Code generated by protoc-gen-gogogo. DO NOT EDIT.
import (
    "net/http"
    "strings"
)

const API_JSON = "[{\"Package\":\"helloworld\",\"Service\":\"Greeter\",\"Method\":{\"name\":\"SayHello\",\"input_type\":\".helloworld.HelloRequest\",\"output_type\":\".helloworld.HelloReply\",\"options\":{}},\"InputTypeDescriptor\":{\"name\":\"HelloRequest\",\"field\":[{\"name\":\"name\",\"number\":1,\"label\":1,\"type\":9,\"json_name\":\"name\"},{\"name\":\"age\",\"number\":2,\"label\":1,\"type\":9,\"json_name\":\"age\"}]},\"Pattern\":{\"Verb\":\"GET\",\"Path\":\"/v2/hello/{name}/{age}\",\"Body\":\"\"},\"Options\":{}},{\"Package\":\"helloworld\",\"Service\":\"Greeter\",\"Method\":{\"name\":\"SayBye\",\"input_type\":\".helloworld.HelloRequest\",\"output_type\":\".helloworld.HelloReply\",\"options\":{}},\"InputTypeDescriptor\":{\"name\":\"HelloRequest\",\"field\":[{\"name\":\"name\",\"number\":1,\"label\":1,\"type\":9,\"json_name\":\"name\"},{\"name\":\"age\",\"number\":2,\"label\":1,\"type\":9,\"json_name\":\"age\"}]},\"Pattern\":{\"Verb\":\"PUT\",\"Path\":\"/v2/bye\",\"Body\":\"*\"},\"Options\":{}},{\"Package\":\"helloworld\",\"Service\":\"Greeter\",\"Method\":{\"name\":\"SayHi\",\"input_type\":\".helloworld.HiRequest\",\"output_type\":\".helloworld.HiReply\",\"options\":{}},\"InputTypeDescriptor\":{\"name\":\"HiRequest\",\"field\":[{\"name\":\"content\",\"number\":1,\"label\":1,\"type\":9,\"json_name\":\"content\"}]},\"Pattern\":{\"Verb\":\"PUT\",\"Path\":\"/v2/hi\",\"Body\":\"*\"},\"Options\":{}}]"

func init() {
	if _, err := (&http.Client{}).Post("http://api-gateway:8080/rules", "", strings.NewReader(API_JSON)); err != nil {
		panic(err)
	}
}